environments:
- name: msp-pipeline-example-acceptance
  cluster:
    imageId: ami-d2163bb7
  vpcTarget:
    vpcId: vpc-9aa942f3
    instanceSubnetIds:
      - subnet-407f570a
      - subnet-8332c4ea
      - subnet-ee707896
    elbSubnetIds:
      - subnet-407f570a
      - subnet-8332c4ea
      - subnet-ee707896
- name: msp-pipeline-example-production
  vpcTarget:
    vpcId: vpc-9aa942f3
    instanceSubnetIds:
      - subnet-407f570a
      - subnet-8332c4ea
      - subnet-ee707896
    elbSubnetIds:
      - subnet-407f570a
      - subnet-8332c4ea
      - subnet-ee707896
service:
  name: msp-pipeline-example
  port: 80
  pathPatterns:
  - /*
  pipeline:
    source:
      provider: GitHub
      repo: stelligent/msp-pipeline-example
    acceptance:
      environment: msp-pipeline-example-acceptance
      image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
      type: linuxContainer
    production:
      environment: msp-pipeline-example-production
      image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
      type: linuxContainer
templates:
  mu-environment-msp-pipeline-example-acceptance:
    Resources:
      S3TestBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: "jimtest-s3-bucket"
#      CodePipelineSNSTopic:
#        Type: AWS::SNS::Topic
#        Properties:
#          Subscription:
#            - Endpoint: "jim.rohrer@stelligent.com"
#              Protocol: email
#      PipelineFailureEventRule:
#        Type: "AWS::Events::Rule"
#        Properties:
#          Description: "Failure notification for msp pipeline"
#          EventPattern:
#            source:
#              - "aws.codepipeline"
#            detail-type:
#              - "CodePipeline Pipeline Execution State Change"
#            detail:
#              state:
#                - "FAILED"
#              pipeline:
#                - Ref: Pipeline
#          State: ENABLED
#          Targets:
#            - Arn:
#                Ref: CodePipelineSNSTopic
#              Id: kqed-pipeline-topic
#              InputTransformer:
#                InputPathsMap:
#                  pipeline: "$.detail.pipeline"
#                  executionid: "$.detail.execution-id"
#                InputTemplate: '"The Pipeline <pipeline> has failed with execution-id: <executionid>."'
